### ISSUE TITLE
ERD for testbed infrastructure

### ISSUE THREAD

**Issue by yash-puligundla** [ga4gh/ga4gh-testbed-infrastructure#1]
Create an ERD for the testbed reports. The report structure is defined in [ga4gh-testbed-lib](https://github.com/ga4gh/ga4gh-testbed-lib).

**Comment by jb-adams** [comment]
Looks great so far Yash!

A couple requests for this branch:
* Can you also add a `database/sqlite` and creation + dev dataset population sql scripts?
* Can you add a `Makefile` to allow quick cleanup and re-instantiation of a test, sqlite database? Essentially what we have for the [starter kit](https://github.com/ga4gh/ga4gh-starter-kit-drs/blob/develop/Makefile)

Just FYI, I started a [branch](https://github.com/ga4gh/ga4gh-testbed-infrastructure/tree/feature/issue-2-initial-app) off of yours for our "hackathon" this afternoon, basically starting the Java app, some models/entities, and some dummy controllers.

**Comment by jb-adams** [comment]
Closing issue as #3 was successfully merged
